// export const DASHBOARD_SOCKET_BASE_URL = "wss://sa3dni.herokuapp.com/";
export const DASHBOARD_SOCKET_BASE_URL = "ws://192.168.0.206:7001/";
export const DASHBOARD_SOCKET_AUTH_QP = "token";


//LISTEN EVENTS
export const DASHBOARD_CHAT_ASSIGNED_SOCKET_EVENT = "chat-assigned";
export const DASHBOARD_CHAT_CLOSED_SOCKET_EVENT = "chat-closed";
export const DASHBOARD_CHAT_MESSAGE_SOCKET_EVENT = "chat-message";


//EMIT EVENTS
export const DASHBOARD_JOIN_CHAT_SOCKET_EVENT = "join-chat";
export const DASHBOARD_SEND_MESSAGE_SOCKET_EVENT = "send-message";


export default {
  DASHBOARD_SOCKET_BASE_URL,
  DASHBOARD_CHAT_MESSAGE_SOCKET_EVENT,
  DASHBOARD_CHAT_ASSIGNED_SOCKET_EVENT,
  DASHBOARD_CHAT_CLOSED_SOCKET_EVENT,
  DASHBOARD_JOIN_CHAT_SOCKET_EVENT,
};
