import {DASHBOARD_SOCKET_PREFIX} from "../../store/constants";
import {WEBSOCKET_CONNECT, WEBSOCKET_DISCONNECT, WEBSOCKET_SEND} from "./actionTypes";

// Socket defined, user actions to dispatch

export const DASHBOARD_SOCKET_CONNECT = `${DASHBOARD_SOCKET_PREFIX}::${WEBSOCKET_CONNECT}`;
export const DASHBOARD_SOCKET_DISCONNECT = `${DASHBOARD_SOCKET_PREFIX}::${WEBSOCKET_DISCONNECT}`;

export const DASHBOARD_SOCKET_SEND = `${DASHBOARD_SOCKET_PREFIX}::${WEBSOCKET_SEND}`;