export const Routes = {
  BASE: "/",
  REGISTER_OWNER: "/register",
  REGISTER_AGENT: "/join",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  CHATS: "/chats",
  WORKSPACE: "/workspace",
  AGENTS: "/agents",
  INVITES: "/invites",
  GROUPS: "/groups",
  REPORTS: "/reports",
  REPORTS_CHATS_SATISFACTION: "/chats/satisfaction",
  REPORTS_CHATS_AVAILABILITY: "/chats/availability",
  REPORTS_AGENT_SATISFACTION: "/agents/satisfaction",
  PARAM_AGENT_ID: "agentId",
  PARAM_GROUP_ID: "groupId",
  PARAM_CHAT_ID: "chatId",
};
